name: Deploy Tolle UI & Storybook

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build Angular App (tolle-ui)
        run: |
          npm run build:web

      - name: Build Storybook (tolle-ui-docs)
        run: |
          npm run build:storybook

      - name: Deploy Angular App to AWS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          source: dist/showcase/browser/*
          target: /var/www/tolle-ui
          strip_components: 3

      - name: Deploy Storybook to AWS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          source: dist/storybook/tolle/*
          target: /var/www/tolle-ui-docs
          strip_components: 3
